allprojects {
    apply plugin: 'maven-publish'
}

subprojects {
    repositories {
        mavenLocal()
        mavenCentral()
        jcenter()
    }
}

evaluationDependsOn ":universal"
evaluationDependsOn ":java"

publishing {
    publications {
        maven(MavenPublication) {
            groupId = 'com.msopentech.thali'
            version = '0.0.6-SNAPSHOT'
        }
    }
}
